### ISSUE TITLE
AttributeError: 'dict' object has no attribute '_sort_key' with iso-codes-4.2

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/translation-finder#9]
after launching my script again with the last two patches you just wrote (thank you again), I have a regression, it makes it crash with iso-codes:

```
extract_srpm: ./src.rpms/f30/iso-codes-4.2-2.fc30.src.rpm
discover_translations: /tmp/tmpah3onmyv
Traceback (most recent call last):
  File "./build.py", line 143, in <module>
    main()
  File "./build.py", line 44, in main
    discover_translations(tmp, package)
  File "./build.py", line 65, in discover_translations
    translation_files = discover(tmp)
  File "/home/jb/Projects/fedora-l10n/translation-finder/translation_finder/api.py", line 68, in discover
    return list(sorted(results))
  File "/home/jb/Projects/fedora-l10n/translation-finder/translation_finder/discovery/base.py", line 58, in __gt__
    return self._sort_key > other._sort_key
AttributeError: 'dict' object has no attribute '_sort_key'
```

Previous result was:
```
[
   {
      'filemask':'iso_15924/*.po',
      'new_base':'iso_15924/iso_15924.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_3166-1/*.po',
      'new_base':'iso_3166-1/iso_3166-1.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_3166-2/*.po',
      'new_base':'iso_3166-2/iso_3166-2.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_3166-2/*.po',
      'template':'iso_3166-2/en.po',
      'new_base':'iso_3166-2/iso_3166-2.pot',
      'file_format':'po-mono'
   },
   {
      'filemask':'iso_3166-3/*.po',
      'new_base':'iso_3166-3/iso_3166-3.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_4217/*.po',
      'new_base':'iso_4217/iso_4217.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_639-2/*.po',
      'new_base':'iso_639-2/iso_639-2.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_639-3/*.po',
      'new_base':'iso_639-3/iso_639-3.pot',
      'file_format':'po'
   },
   {
      'filemask':'iso_639-5/*.po',
      'new_base':'iso_639-5/iso_639-5.pot',
      'file_format':'po'
   }
]
```

Here are the files: [files.txt](https://github.com/WeblateOrg/translation-finder/files/3124419/files.txt). Upstream code is there: https://salsa.debian.org/iso-codes-team/iso-codes

To pull your new code, I removed my virtualenv, did git pull in my folder and made `pip install -r requirements.txt && pip install -e .`

Thanks a lot for your help!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by Jibec** [comment]
thank you magic-nijel :heart:
